### ISSUE TITLE
Failed at RN 5.1

### ISSUE THREAD

**Issue by thinhvo-groove** [kadiks/react-native-itunes#11]
I had tested your library using RN version 5.1 and found that it failed. Can you support RN 5.1?

**Comment by kadiks** [comment]
It failed. Ok, do you have details?

I will assume that you meant RN 0.51 and check it later this week.

Thanks for reporting the issue

**Comment by thinhvo-groove** [comment]
@kadiks Hey, It was my mistakes that I didn't include NSAppleMusicUsageDescription to info.list. Thanks for your support !
