### ISSUE TITLE
artwork file path

### ISSUE THREAD

**Issue by thinhvo-groove** [kadiks/react-native-itunes#12]
Hello, your library returns a base64 image which is really heavy to store on devices. I would like to get the file path instead of base64 string image. Can you do something to support me?

**Comment by kadiks** [comment]
As far as I remember, they do not give access to the file path (that would have been much simpler for me too).

In the meantime, if anyone else has an idea, I'm open for suggestions.

I will have another go at it next week to be sure I didn't overlook anything before closing.

**Comment by kadiks** [comment]
Not possible, as far as I know.

The workaround would be for you to actually save each images in your app local folder and save that path. I know it's duplicating content but that's the closest you can do.
