### ISSUE TITLE
expand library search to complete Apple Music catalogue?

### ISSUE THREAD

**Issue by alexichristakis** [kadiks/react-native-itunes#19]
Hi! Great library, but I'm wondering if we can take pieces from this repository:

https://github.com/Maelstroms38/react-native-apple-music/blob/master/ios/RNAppleMusic.m

and enable react-native-itunes to also query the Apple Music database. Is this something you've looked into?

**Comment by kadiks** [comment]
Hi,

Indeed, I might need it for the next version of an app I'm working on. Thanks for putting it under my radar.
What would be your use case so I can think of a standard solution?

**Comment by alexichristakis** [comment]
finding and playing songs not in a users library through a third-party app.

**Comment by kadiks** [comment]
Same use case as mine, cool.

If I do work on this, it won't be before 2-3 months, so if you want to include a PR until then, that would be awesome.

In the meantime, I'll add it to the roadmap.
