### ISSUE TITLE
Error when retriving tracks with genre or artist fields

### ISSUE THREAD

**Issue by indesignlatam** [kadiks/react-native-itunes#2]
First of all good job with this pacakge, it has been very usefull.

I have found some error when trying yo getTracks with genre and artist fields, the error is caused when a song has no artist o no genre.

I have fix the issue by adding the following as you do with the composer field

````
...
if ([fields containsObject: @"artist"]) {
    NSString *artist = [song valueForProperty: MPMediaItemPropertyArtist]; // filterable
    if (artist == nil) {
        artist = @"";
    }
    [songDictionary setValue:[NSString stringWithString:artist] forKey:@"artist"];
}
...
if ([fields containsObject: @"genre"]) {
    if (genre == nil) {
        genre = @"";
    }
    [songDictionary setValue:[NSString stringWithString:genre] forKey:@"genre"];
}
````

If you think this is the best approach i can make a pull request with the fixes.

**Comment by kadiks** [comment]
Hola !
Good catch.
I actually use only Apple Music songs, so I didn't thought of imported music cases.

Your approach is exactly what I would do. That would be awesome if you could do the PR.

Thanks!!!

**Comment by indesignlatam** [comment]
Thats great, i will send the PR as soon as posible.
