### ISSUE TITLE
Cannot run on iOS 10.2

### ISSUE THREAD

**Issue by ospfranco** [kadiks/react-native-itunes#4]
I added the library (first got a crash because you need to add permissions now), called getTracks and immediately got this:

![img_5953](https://cloud.githubusercontent.com/assets/1634213/21481589/bdffd5f4-cb69-11e6-9265-9231866d77f0.PNG)

Any suggestions?

**Comment by ospfranco** [comment]
Ah, I see latest release does not contain one of the fixes for nil fields, might be a good idea to release it ;)

**Comment by ospfranco** [comment]
At first I thought this was fixed by the commit made by indesignlatam, but it seems it is not...

**Comment by ospfranco** [comment]
I have managed to get around this using this following code:

```
iTunes.getTracks({'fields': ['title']})
    .then((tracks) => {
      this.tracks = tracks;
    });
```

Seems validation on empty fields need to improve

**Comment by kadiks** [comment]
Perfect for the workaround.

I'll update the repo this week with the issue you talked about:
- iOS 10 permissions
- Fields validation

**Comment by kadiks** [comment]
- Permissions are updated in the README
- Fields validation are published in NPM / 0.4.2

I couldn't reproduce your bug, so if it's still there, I would need more details on the field that create that bug.

**Comment by ospfranco** [comment]
I have like 60 files with only title and artist name set, part of a ripped collection.

**Comment by kadiks** [comment]
Ok, I see.
Is the new code fixes your issue?

**Comment by ospfranco** [comment]
Haven't tried it yet, new years celebration ;), I will try it on the weekend and let you know, thanks for the help!

**Comment by ospfranco** [comment]
It seems to be working perfectly now! many thanks!
